name:                ghcjslib-demo
version:             0.1.0.0
github:              "flbulgarelli/ghcjslib-demo"
license:             BSD3
author:              "Franco Leonardo Bulgarelli"
maintainer:          "franco@mumuki.org"
copyright:           "2018 Franco Leonardo Bulgarelli"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flbulgarelli/ghcjslib>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ghcjslib-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghcjslib-demo
    - ghcjs-base

tests:
  ghcjslib-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghcjslib-demo


